name: Docker CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ vars.SERVER_IP }}         
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      IMAGE_NAME: myapp
      CONTAINER_NAME: myapp

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build & Push Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/myapp:latest .
          docker push $DOCKER_USERNAME/myapp:latest

      # Configure SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      # Add EC2 Private Key
      - name: Add SSH Key
        run: |
          echo $SSH_KEY64 | base64 -d > mykey.pem
          chmod 400 mykey.pem
        env:
          SSH_KEY64: ${{ secrets.SSH_KEY64 }}

      # Deploy to EC2
      - name: Deploy to EC2
        run: |
          echo "Deploying to EC2 at $SERVER_IP"
          ssh -i mykey.pem -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "\
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} &&
            docker ps -aq -f name=$CONTAINER_NAME | xargs -r docker rm -f &&
            docker pull $DOCKER_USERNAME/myapp:latest && \
            docker run -d -p 80:3000 --name myapp $DOCKER_USERNAME/myapp:latest"

